server:
  port: 8200
spring:
  application:
    name: rest-items
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #    url: jdbc:h2:mem:mydb
  #    username: sa
  #    driverClassName: org.h2.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
#rest-products:
#  ribbon:
#    listOfServers: localhost:8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
    instances:
      items:
        base-config: defecto
